"""first migrate

Revision ID: 167b6c13fcbb
Revises: 
Create Date: 2020-06-19 04:42:00.568193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167b6c13fcbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    # ### end Alembic commands ###
